### ISSUE TITLE
Add basic tests

### ISSUE THREAD

**Issue by irbekrm** [cert-manager/testing-addons#2]
As this repo will mostly contain Terraform files, we could have a basic test that runs Terraform linter.

**Comment by irbekrm** [comment]
@lonelyCZ maybe it makes more sense to first work on #4 ? I don't know if we can add a linter if there are no Terraform files in this repository yet. Up to you though!

**Comment by lonelyCZ** [comment]
> maybe it makes more sense to first work on https://github.com/cert-manager/testing-addons/issues/4 ?

Yes, I think so.

**Comment by lonelyCZ** [comment]
Hi @irbekrm , is there a best practice of `terraform linter`? If not, I am going to research it.

**Comment by irbekrm** [comment]
Hi, I think perhaps just running `terraform validate` is sufficient? At least for start.
