### ISSUE TITLE
Run test (linter) in CI

### ISSUE THREAD

**Issue by irbekrm** [cert-manager/testing-addons#3]
The test that was added in #2  should run on every PR. We could do that via Github actions.

**Comment by lonelyCZ** [comment]
Hi @irbekrm , how to add this CI? [here](https://github.com/jetstack/testing)?

**Comment by irbekrm** [comment]
Hi, I think for now it should be sufficient to add a [Github action](https://docs.github.com/en/actions) that [runs on pull requests against master branch](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#using-events-to-trigger-workflows).

**Comment by irbekrm** [comment]
For example see the GH Actions workflows in https://github.com/cert-manager/aws-privateca-issuer/tree/main/.github/workflows
