### ISSUE TITLE
Create a single variables file for cert-manager + Vault workflow

### ISSUE THREAD

**Issue by irbekrm** [cert-manager/testing-addons#7]
At the moment 4 are three separate vars files in `./cm-vault/*`.

We should have a single file, so that if users want to, for example, provide a different kube config file path, they only need to specify it in one place.

(I assume that it is possible to pass a variables file to `terragrunt run-all apply` command)

**Comment by lonelyCZ** [comment]
> I assume that it is possible to pass a variables file to terragrunt run-all apply command

I justed research it yesterday, it should do at https://terragrunt.gruntwork.io/docs/features/keep-your-cli-flags-dry/#required-and-optional-var-files
